In [222]:
import tensorflow as tf
import numpy as np

from numpy.random import RandomState

In [242]:
## class making done
## safe input and output
class DRRAveStateRepresentation(tf.keras.Model):
    def __init__(self, n_items=5, item_features=100, user_features=100):
        super(DRRAveStateRepresentation, self).__init__()
        ## initialize random_state to 1
        self.random_state = RandomState(1)
        
        ## hold all the parameters variable
        self.n_items = n_items
        self.item_features = item_features
        self.user_features = user_features
        
        ## add to the model parameter
        self.attention_weights = tf.Variable(initial_value=(0.1 * self.random_state.rand(self.n_items)),
                                             trainable=True,
                                             dtype='float32')
        
    def call(self, user, items):
        '''
        items  : type(tensor) shape = (n_items x item_features)
        user   : type(tensor) shape = (user_features)
        output : type(tensor) shape = (3 x item_features)
        '''
        ## right will result in numpy array
        ## because there is an issue with tensor matrix multiplications
        right = tf.transpose(items).numpy() @ self.attention_weights.numpy()
        middle = user * right
        output = tf.concat([user, middle, right], 0).numpy().flatten()
        return tf.convert_to_tensor(output)

In [248]:
state_rep.summary()

Model: "drr_ave_state_representation_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________


In [226]:
n_items = 5
user_features = 100
item_features = 100

In [227]:
user = tf.convert_to_tensor(np.random.rand(100, ))
item = tf.convert_to_tensor(np.random.rand(5, 100))

In [243]:
state_rep = DRRAveStateRepresentation(5, 100, 100)

In [244]:
state_rep(user, item)

<tf.Tensor: shape=(300,), dtype=float32, numpy=
array([5.25641918e-01, 3.37380797e-01, 3.42687070e-01, 3.08361918e-01,
       3.00802469e-01, 1.99843884e-01, 1.99741349e-01, 3.53729308e-01,
       6.54267192e-01, 8.51159573e-01, 8.60902071e-01, 3.89494210e-01,
       8.56851399e-01, 1.24891363e-02, 2.50641108e-01, 1.83446869e-01,
       7.51140356e-01, 3.07510972e-01, 4.38658074e-02, 8.59275162e-01,
       2.76567310e-01, 6.96427524e-01, 8.90311897e-02, 3.94686282e-01,
       6.01303041e-01, 8.64767909e-01, 1.41753897e-01, 9.17562544e-01,
       8.11112881e-01, 5.15697539e-01, 7.73163199e-01, 5.73115587e-01,
       6.34342968e-01, 5.13679981e-01, 1.31707750e-02, 3.59406501e-01,
       1.45767063e-01, 6.31664693e-01, 3.83711338e-01, 2.22943589e-01,
       1.59132957e-01, 3.80246520e-01, 9.04872715e-01, 1.39637560e-01,
       3.17646056e-01, 3.49199504e-01, 3.39182973e-01, 7.35604644e-01,
       2.30612576e-01, 7.94375658e-01, 7.44697988e-01, 6.72630742e-02,
       4.77214724e-01, 9.9217

In [224]:
attention_weights = tf.Variable(initial_value=(0.1 * np.random.rand(n_items)),
                                             trainable=False,
                                             dtype='float32')

attention_weights

<tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=
array([0.07795722, 0.04622126, 0.0070302 , 0.06819446, 0.06454879],
      dtype=float32)>

In [186]:
items = np.random.rand(5, 3)

In [188]:
items

array([[0.38094765, 0.71926223, 0.75050159],
       [0.72559223, 0.90325514, 0.72327553],
       [0.25491091, 0.42000141, 0.12541389],
       [0.06694736, 0.01405626, 0.3655533 ],
       [0.18668715, 0.5615523 , 0.9243705 ]])

In [192]:
user = np.random.rand(3,)

In [147]:
right = tf.transpose(items).numpy() @ att
right

array([0.08900728, 0.02382631, 0.02372153, 0.04766469, 0.02777875])

In [182]:
attention_weights = tf.Variable(initial_value=(0.1 * np.random.rand(5)),
                                             trainable=True,
                                             dtype='float32')

In [185]:
attention_weights.numpy()

array([0.07940327, 0.09050804, 0.02643326, 0.0552509 , 0.00515117],
      dtype=float32)

In [189]:
tf.transpose(items).numpy()

array([[0.38094765, 0.72559223, 0.25491091, 0.06694736, 0.18668715],
       [0.71926223, 0.90325514, 0.42000141, 0.01405626, 0.5615523 ],
       [0.75050159, 0.72327553, 0.12541389, 0.3655533 , 0.9243705 ]])

In [193]:
middle = user * right
middle

array([0.03772245, 0.11911626, 0.04324372])

In [194]:
right

array([0.1073191 , 0.1536349 , 0.15332837])

In [202]:
output = tf.concat([user, middle, right], 0).numpy().flatten()

In [203]:
tf.convert

array([0.35149795, 0.77532027, 0.28203341, 0.03772245, 0.11911626,
       0.04324372, 0.1073191 , 0.1536349 , 0.15332837])